import type {
  Material,
  Class,
  ClassStudent,
  Chapter,
  Exam,
  Question,
  Submission,
  Conversation,
  Message,
} from '@/types';

// ==================== MATERIALS ====================
export const mockMaterials: Material[] = [
  {
    id: 'm1',
    title: 'Sách Toán lớp 6 - Tập 1',
    description: 'Sách giáo khoa Toán lớp 6 tập 1, bao gồm các chương: Số tự nhiên, Phân số, Hình học.',
    thumbnail_url: 'https://picsum.photos/seed/math1/400/300',
    file_url: '/uploads/materials/toan6-t1.pdf',
    material_type: 'book',
    subject: 'Toán',
    grade: 'Lớp 6',
    is_system: true,
    created_by: 'system',
    created_at: '2026-01-15T08:00:00Z',
  },
  {
    id: 'm2',
    title: 'Đề kiểm tra Toán 15 phút',
    description: 'Đề kiểm tra 15 phút chương 1: Số tự nhiên và các phép tính.',
    thumbnail_url: 'https://picsum.photos/seed/math2/400/300',
    file_url: '/uploads/materials/kt15-toan.pdf',
    material_type: 'exam',
    subject: 'Toán',
    grade: 'Lớp 6',
    is_system: false,
    created_by: 'teacher1',
    created_at: '2026-02-01T10:00:00Z',
  },
  {
    id: 'm3',
    title: 'Video bài giảng: Phân số',
    description: 'Video bài giảng về phân số, cách quy đồng và so sánh phân số.',
    thumbnail_url: 'https://picsum.photos/seed/math3/400/300',
    file_url: '/uploads/materials/phanso.mp4',
    material_type: 'video',
    subject: 'Toán',
    grade: 'Lớp 6',
    is_system: false,
    created_by: 'teacher1',
    created_at: '2026-02-10T14:00:00Z',
  },
  {
    id: 'm4',
    title: 'Sách Ngữ Văn lớp 6 - Tập 1',
    description: 'Sách giáo khoa Ngữ Văn lớp 6 tập 1 với các bài đọc hiểu và tập làm văn.',
    thumbnail_url: 'https://picsum.photos/seed/vn1/400/300',
    file_url: '/uploads/materials/van6-t1.pdf',
    material_type: 'book',
    subject: 'Ngữ Văn',
    grade: 'Lớp 6',
    is_system: true,
    created_by: 'system',
    created_at: '2026-01-15T08:00:00Z',
  },
  {
    id: 'm5',
    title: 'Bài tập Tiếng Anh - Unit 1',
    description: 'Bài tập thực hành Tiếng Anh Unit 1: My new school.',
    thumbnail_url: 'https://picsum.photos/seed/eng1/400/300',
    file_url: '/uploads/materials/eng-unit1.pdf',
    material_type: 'document',
    subject: 'Tiếng Anh',
    grade: 'Lớp 6',
    is_system: false,
    created_by: 'teacher1',
    created_at: '2026-02-15T09:00:00Z',
  },
  {
    id: 'm6',
    title: 'Tham khảo: Lịch sử Việt Nam',
    description: 'Tài liệu tham khảo về lịch sử Việt Nam thời kỳ dựng nước.',
    thumbnail_url: 'https://picsum.photos/seed/hist1/400/300',
    file_url: '/uploads/materials/lichsu-vn.pdf',
    material_type: 'reference',
    subject: 'Lịch sử',
    grade: 'Lớp 6',
    is_system: true,
    created_by: 'system',
    created_at: '2026-01-20T11:00:00Z',
  },
  {
    id: 'm7',
    title: 'Video: Thí nghiệm Khoa học',
    description: 'Video hướng dẫn thí nghiệm về sự bay hơi và ngưng tụ.',
    thumbnail_url: 'https://picsum.photos/seed/sci1/400/300',
    file_url: '/uploads/materials/thinghiem.mp4',
    material_type: 'video',
    subject: 'Khoa học',
    grade: 'Lớp 6',
    is_system: false,
    created_by: 'teacher1',
    created_at: '2026-02-20T15:00:00Z',
  },
  {
    id: 'm8',
    title: 'Đề thi Văn giữa kỳ',
    description: 'Đề thi giữa kỳ Ngữ Văn lớp 6 - Học kỳ I.',
    thumbnail_url: 'https://picsum.photos/seed/vn2/400/300',
    file_url: '/uploads/materials/van6-gk.pdf',
    material_type: 'exam',
    subject: 'Ngữ Văn',
    grade: 'Lớp 6',
    is_system: false,
    created_by: 'teacher1',
    created_at: '2026-02-25T08:00:00Z',
  },
  {
    id: 'm9',
    title: 'Atlat Địa lý Việt Nam',
    description: 'Atlat Địa lý dùng cho học sinh lớp 6-9.',
    thumbnail_url: 'https://picsum.photos/seed/geo1/400/300',
    file_url: '/uploads/materials/atlat.pdf',
    material_type: 'reference',
    subject: 'Địa lý',
    grade: 'Lớp 6',
    is_system: true,
    created_by: 'system',
    created_at: '2026-01-25T10:00:00Z',
  },
  {
    id: 'm10',
    title: 'Bài giảng Hình học cơ bản',
    description: 'Slide bài giảng về các khái niệm hình học cơ bản: Điểm, đường thẳng, đoạn thẳng.',
    thumbnail_url: 'https://picsum.photos/seed/math4/400/300',
    file_url: '/uploads/materials/hinhoc.pdf',
    material_type: 'document',
    subject: 'Toán',
    grade: 'Lớp 6',
    is_system: false,
    created_by: 'teacher1',
    created_at: '2026-03-01T09:00:00Z',
  },
];

// ==================== CLASSES ====================
export const mockClasses: Class[] = [
  {
    id: 'c1',
    name: 'Lớp 6A',
    description: 'Lớp 6A năm học 2025-2026',
    thumbnail_url: 'https://picsum.photos/seed/class1/400/300',
    teacher_id: 'teacher1',
    teacher_name: 'Nguyễn Văn A',
    join_code: 'EDU6A',
    student_count: 35,
    created_at: '2025-09-01T08:00:00Z',
  },
  {
    id: 'c2',
    name: 'Lớp 6B',
    description: 'Lớp 6B năm học 2025-2026',
    thumbnail_url: 'https://picsum.photos/seed/class2/400/300',
    teacher_id: 'teacher1',
    teacher_name: 'Nguyễn Văn A',
    join_code: 'EDU6B',
    student_count: 32,
    created_at: '2025-09-01T08:00:00Z',
  },
  {
    id: 'c3',
    name: 'Lớp 7A',
    description: 'Lớp 7A năm học 2025-2026',
    thumbnail_url: 'https://picsum.photos/seed/class3/400/300',
    teacher_id: 'teacher1',
    teacher_name: 'Nguyễn Văn A',
    join_code: 'EDU7A',
    student_count: 30,
    created_at: '2025-09-01T08:00:00Z',
  },
  {
    id: 'c4',
    name: 'Lớp Tiếng Anh nâng cao',
    description: 'Lớp học Tiếng Anh nâng cao cho học sinh giỏi',
    thumbnail_url: 'https://picsum.photos/seed/class4/400/300',
    teacher_id: 'teacher1',
    teacher_name: 'Nguyễn Văn A',
    join_code: 'EDUEA',
    student_count: 20,
    created_at: '2025-09-15T08:00:00Z',
  },
  {
    id: 'c5',
    name: 'Lớp Toán thi HSG',
    description: 'Lớp bồi dưỡng Toán thi học sinh giỏi',
    thumbnail_url: 'https://picsum.photos/seed/class5/400/300',
    teacher_id: 'teacher1',
    teacher_name: 'Nguyễn Văn A',
    join_code: 'EDUHSG',
    student_count: 15,
    created_at: '2025-10-01T08:00:00Z',
  },
];

// ==================== STUDENTS ====================
export const mockStudents: ClassStudent[] = [
  { id: 's1', student_id: 'u2', full_name: 'Trần Văn B', email: 'tranb@edu.vn', joined_at: '2025-09-02T08:00:00Z' },
  { id: 's2', student_id: 'u3', full_name: 'Lê Thị C', email: 'lethic@edu.vn', joined_at: '2025-09-02T08:00:00Z' },
  { id: 's3', student_id: 'u4', full_name: 'Phạm Văn D', email: 'phamd@edu.vn', joined_at: '2025-09-03T08:00:00Z' },
  { id: 's4', student_id: 'u5', full_name: 'Hoàng Thị E', email: 'hoange@edu.vn', joined_at: '2025-09-03T08:00:00Z' },
  { id: 's5', student_id: 'u6', full_name: 'Ngô Văn F', email: 'ngof@edu.vn', joined_at: '2025-09-04T08:00:00Z' },
  { id: 's6', student_id: 'u7', full_name: 'Đỗ Thị G', email: 'dothig@edu.vn', joined_at: '2025-09-04T08:00:00Z' },
  { id: 's7', student_id: 'u8', full_name: 'Vũ Văn H', email: 'vuvanh@edu.vn', joined_at: '2025-09-05T08:00:00Z' },
];

// ==================== CHAPTERS ====================
export const mockChapters: Chapter[] = [
  {
    id: 'ch1',
    class_id: 'c1',
    name: 'Chương 1: Số tự nhiên',
    order_index: 1,
    materials: [mockMaterials[0], mockMaterials[9]],
  },
  {
    id: 'ch2',
    class_id: 'c1',
    name: 'Chương 2: Phân số',
    order_index: 2,
    materials: [mockMaterials[2]],
  },
  {
    id: 'ch3',
    class_id: 'c1',
    name: 'Chương 3: Hình học cơ bản',
    order_index: 3,
    materials: [mockMaterials[9]],
  },
];

// ==================== EXAMS ====================
export const mockExams: Exam[] = [
  {
    id: 'e1',
    class_id: 'c1',
    title: 'Kiểm tra Toán giữa kỳ',
    description: 'Bài kiểm tra giữa kỳ môn Toán lớp 6A - Học kỳ II',
    thumbnail_url: 'https://picsum.photos/seed/exam1/400/300',
    start_time: '2026-03-10T08:00:00Z',
    end_time: '2026-03-10T09:30:00Z',
    status: 'upcoming',
    created_by: 'teacher1',
    created_at: '2026-03-01T10:00:00Z',
    question_count: 10,
  },
  {
    id: 'e2',
    class_id: 'c1',
    title: 'Kiểm tra 15 phút - Phân số',
    description: 'Bài kiểm tra 15 phút về phân số',
    thumbnail_url: 'https://picsum.photos/seed/exam2/400/300',
    start_time: '2026-03-05T08:00:00Z',
    end_time: '2026-03-05T08:15:00Z',
    status: 'open',
    created_by: 'teacher1',
    created_at: '2026-03-01T10:00:00Z',
    question_count: 5,
  },
  {
    id: 'e3',
    class_id: 'c2',
    title: 'Kiểm tra Văn 15 phút',
    description: 'Kiểm tra đọc hiểu văn bản',
    thumbnail_url: 'https://picsum.photos/seed/exam3/400/300',
    start_time: '2026-03-12T08:00:00Z',
    end_time: '2026-03-12T08:15:00Z',
    status: 'upcoming',
    created_by: 'teacher1',
    created_at: '2026-03-02T10:00:00Z',
    question_count: 3,
  },
  {
    id: 'e4',
    class_id: 'c1',
    title: 'Kiểm tra Toán chương 1',
    description: 'Kiểm tra tổng hợp chương 1 - Số tự nhiên',
    thumbnail_url: 'https://picsum.photos/seed/exam4/400/300',
    start_time: '2026-02-20T08:00:00Z',
    end_time: '2026-02-20T09:00:00Z',
    status: 'closed',
    created_by: 'teacher1',
    created_at: '2026-02-15T10:00:00Z',
    question_count: 8,
  },
];

// ==================== QUESTIONS ====================
export const mockQuestions: Question[] = [
  {
    id: 'q1',
    exam_id: 'e2',
    type: 'single_choice',
    content: 'Kết quả của phép tính 1/2 + 1/3 là bao nhiêu?',
    instruction: 'Chọn đáp án đúng',
    points: 2,
    required: true,
    order_index: 1,
    options: [
      { id: 'o1', content: '2/5', is_correct: false },
      { id: 'o2', content: '5/6', is_correct: true },
      { id: 'o3', content: '1/6', is_correct: false },
      { id: 'o4', content: '2/6', is_correct: false },
    ],
  },
  {
    id: 'q2',
    exam_id: 'e2',
    type: 'multi_choice',
    content: 'Các phân số nào sau đây bằng 1/2?',
    instruction: 'Chọn tất cả đáp án đúng',
    points: 3,
    required: true,
    order_index: 2,
    options: [
      { id: 'o5', content: '2/4', is_correct: true },
      { id: 'o6', content: '3/6', is_correct: true },
      { id: 'o7', content: '2/3', is_correct: false },
      { id: 'o8', content: '5/10', is_correct: true },
    ],
  },
  {
    id: 'q3',
    exam_id: 'e2',
    type: 'text',
    content: 'Giải thích cách quy đồng mẫu số của hai phân số 1/3 và 1/4.',
    instruction: 'Viết đầy đủ các bước',
    points: 5,
    required: true,
    order_index: 3,
    options: [],
  },
  {
    id: 'q4',
    exam_id: 'e2',
    type: 'single_choice',
    content: 'Phân số 3/4 lớn hơn phân số nào sau đây?',
    points: 2,
    required: true,
    order_index: 4,
    options: [
      { id: 'o9', content: '4/5', is_correct: false },
      { id: 'o10', content: '2/3', is_correct: true },
      { id: 'o11', content: '5/6', is_correct: false },
      { id: 'o12', content: '7/8', is_correct: false },
    ],
  },
  {
    id: 'q5',
    exam_id: 'e2',
    type: 'single_choice',
    content: 'Kết quả của 2/5 × 5/3 là?',
    points: 2,
    required: true,
    order_index: 5,
    options: [
      { id: 'o13', content: '2/3', is_correct: true },
      { id: 'o14', content: '10/15', is_correct: false },
      { id: 'o15', content: '7/8', is_correct: false },
      { id: 'o16', content: '1/3', is_correct: false },
    ],
  },
];

// ==================== SUBMISSIONS ====================
export const mockSubmissions: Submission[] = [
  {
    id: 'sub1',
    exam_id: 'e4',
    student_id: 'u2',
    student_name: 'Trần Văn B',
    started_at: '2026-02-20T08:00:00Z',
    submitted_at: '2026-02-20T08:45:00Z',
    total_score: 8,
    status: 'graded',
    answers: [],
  },
  {
    id: 'sub2',
    exam_id: 'e4',
    student_id: 'u3',
    student_name: 'Lê Thị C',
    started_at: '2026-02-20T08:00:00Z',
    submitted_at: '2026-02-20T08:50:00Z',
    total_score: 9.5,
    status: 'graded',
    answers: [],
  },
  {
    id: 'sub3',
    exam_id: 'e4',
    student_id: 'u4',
    student_name: 'Phạm Văn D',
    started_at: '2026-02-20T08:00:00Z',
    submitted_at: '2026-02-20T08:55:00Z',
    total_score: 7,
    status: 'graded',
    answers: [],
  },
];

// ==================== CONVERSATIONS ====================
export const mockConversations: Conversation[] = [
  {
    id: 'conv1',
    participant: { id: 'u2', full_name: 'Trần Văn B', role: 'student' },
    last_message: 'Thầy ơi, bài này làm thế nào ạ?',
    last_message_at: '2026-03-05T10:30:00Z',
    unread_count: 2,
  },
  {
    id: 'conv2',
    participant: { id: 'u3', full_name: 'Lê Thị C', role: 'student' },
    last_message: 'Em cảm ơn thầy ạ!',
    last_message_at: '2026-03-04T15:00:00Z',
    unread_count: 0,
  },
  {
    id: 'conv3',
    participant: { id: 'u4', full_name: 'Phạm Văn D', role: 'student' },
    last_message: 'Thầy cho em hỏi về bài tập',
    last_message_at: '2026-03-03T09:00:00Z',
    unread_count: 1,
  },
];

export const mockMessages: Message[] = [
  {
    id: 'msg1',
    conversation_id: 'conv1',
    sender_id: 'u2',
    content: 'Thầy ơi, cho em hỏi bài tập về phân số ạ',
    is_read: true,
    created_at: '2026-03-05T10:00:00Z',
  },
  {
    id: 'msg2',
    conversation_id: 'conv1',
    sender_id: 'teacher1',
    content: 'Em chào thầy, em muốn hỏi bài nào nè?',
    is_read: true,
    created_at: '2026-03-05T10:15:00Z',
  },
  {
    id: 'msg3',
    conversation_id: 'conv1',
    sender_id: 'u2',
    content: 'Thầy ơi, bài này làm thế nào ạ?',
    is_read: false,
    created_at: '2026-03-05T10:30:00Z',
  },
  {
    id: 'msg4',
    conversation_id: 'conv1',
    sender_id: 'u2',
    content: 'Bài 5 trang 42, phần quy đồng mẫu số ạ',
    is_read: false,
    created_at: '2026-03-05T10:31:00Z',
  },
];
